version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    deploy:
      replicas: 3
    ports:
      - "3000:80"
